export const attributionList = [
  [ {
    author: 'Icons made by Freepik from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com.',
    link: 'https://www.freepik.com',
    title: 'Freepik'
  },
  {
    author: 'Icons made by Kiranshastry from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com.',
    link: 'https://www.flaticon.com/authors/kiranshastry',
    title: 'Kiranshastry'
  },
  {
    author: 'Icons made by Pixel perfect from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com.',
    link: 'https://www.flaticon.com/authors/pixel-perfect',
    title: 'Pixel perfect'
  } ],
  [// 'https://github.com/lipis/flag-icon-css',
    'https://unsplash.com/photos/jvdzBSV082s?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/lOW7w5-DMHk?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/PzRF6Xb5aAA?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/enVg_Vtsw1c?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/tW0Ix_Ajg6Y?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/1sq8EZgw-D8?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/OlKCes2y1eA?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/OlKCes2y1eA?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/JBIK4QZOFfc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/s8_7AqkzCWY?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Uo8DAAbmB3s?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/5GtLAtUNiow?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/1VEVJrBF94U?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/zURPcpLoKA4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/n4po6S3Movs?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/jxWL76TZQNw?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/2Zlvt-Uf73s?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Y1Ul14Qvdd0?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/CqQsEDCpPqc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/CqQsEDCpPqc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/CqQsEDCpPqc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/yNISa-HXD3E?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/LGNxQzYmeUk?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/VPNO2XAnGB4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/fXAuCMEYGY4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/fXAuCMEYGY4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/fXAuCMEYGY4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/fXAuCMEYGY4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/ppOPjqAJ3Mw?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/OUUeALuq9f4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/cOw_JxasssM?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/khHgeJFHroc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/aX_ljOOyWJY?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/wg6CYRRmwrQ?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/ERGI0DDJXco?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/ySxSlqeC0YM?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/vdx5hPQhXFk?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Id8BO472TbY?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/HHebuDYjP4I?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Tn5ML-Slq1c?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/6iqpLKqeaE0?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Nl8Oa6ZuNcA?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/zk-fclJdGas?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Vvx4kbkubtI?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/kpxsUMA15-4?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/2RXt6CQY_0c?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/_TN1m5R1pFI?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/Jymrgrt4A6Q?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/gKrxflp1wv0?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/sXYqF4oR3_g?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/90HdOlGbjck?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/90HdOlGbjck?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/IJuze-KdTFk?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink',
    'https://unsplash.com/photos/AcikAA7_Qag?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink']
];
