export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHECK_STATE = 'CHECK_STATE';
export const LOAD_DELIVERY_ADDRESSES = 'LOAD_DELIVERY_ADDRESSES';
export const ADD_DELIVERY_ADDRESS = 'ADD_DELIVERY_ADDRESS';
export const REMOVE_DELIVERY_ADDRESS = 'REMOVE_DELIVERY_ADDRESS';
export const CLEAR_ADDRESSES = 'CLEAR_ADDRESSES';
export const SAVE_NAME = 'SAVE_NAME';